-- AlterTable
ALTER TABLE `User` ADD COLUMN `appTheme` VARCHAR(191) NOT NULL DEFAULT 'dark',
    ADD COLUMN `nightMode` VARCHAR(191) NOT NULL DEFAULT 'system',
    ADD COLUMN `nightStartTime` VARCHAR(191) NOT NULL DEFAULT '22:00',
    ADD COLUMN `nightEndTime` VARCHAR(191) NOT NULL DEFAULT '08:00',
    ADD COLUMN `textSize` DOUBLE NOT NULL DEFAULT 1.0,
    ADD COLUMN `messageRadius` INTEGER NOT NULL DEFAULT 16;
